import { Josefin_Sans } from "next/font/google";
import Link from "next/link";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";

const josefin_sans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NuqsAdapter>
      <html lang="en">
        <body className={`${josefin_sans.variable} antialiased`}>
          <nav className="flex gap-2 justify-end items-center h-18 px-5">
            <Link href="/">Home</Link>
            <Link href="/catalog">Catalog</Link>
          </nav>
          {children}
        </body>
      </html>
    </NuqsAdapter>
  );
}
